using merxly.Domain.Enums;
using merxly.Domain.Interfaces;

namespace merxly.Domain.Entities
{
    public class Payment : ICreatedDate, IModifiedDate
    {
        public Guid Id { get; set; }
        public string PaymentIntentId { get; set; } // Generated by Stripe
        public decimal Amount { get; set; }
        public PaymentStatus Status { get; set; }
        public string? StripeCustomerId { get; set; }
        public string? PaymentMethodId { get; set; }
        public string? ReceiptUrl { get; set; } // Generated by Stripe. Ex: https://pay.stripe.com/receipts/...
        public string? FailureMessage { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public DateTime? PaidAt { get; set; }

        // Foreign Keys
        public Guid OrderId { get; set; }

        // Navigation properties
        public Order Order { get; set; }
        public ICollection<Refund> Refunds { get; set; } = new List<Refund>();
    }
}
